# --- Monitor ---
monitor = , preferred, auto, 1

# --- Input ---
input {
    kb_layout = us
    kb_variant = intl
    follow_mouse = 2

    touchpad {
        natural_scroll = true
        tap-to-click = true
        disable_while_typing = true
    }
}

# --- Auto start ---
exec-once = waybar

# --- Main modifier ---
$mainMod = SUPER

# --- Applications ---
bind = CTRL ALT, T, exec, kitty
bind = CTRL ALT, F, exec, zen-browser
bind = $mainMod, SUPER_L, exec, rofi -show drun 

# --- Window management ---
bind = $mainMod, Q, killactive


# --- Window focus ---``
bind = $mainMod, LEFT, movefocus, l
bind = $mainMod, RIGHT, movefocus, r
bind = $mainMod, UP, movefocus, u
bind = $mainMod, DOWN, movefocus, d

# --- Window cycling ---
bind = ALT, TAB, cyclenext
bind = ALT SHIFT, TAB, cyclenext, prev 

# --- Workspaces ---
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

# --- Popup ---
windowrule {
        name = audio-popup
        match:class = audio-popup
        float = true
        size = 460 300
        move = 1440 45
}

windowrule {
    name = network-popup
    match:class = network-popup

    float = true
    size = 600 420
    move = 1300 45
}

windowrule {
    name = battery-popup
    match:class = battery-popup

    float = true
    size = 500 280
    move = 1390 45
}

# --- Exit Hyprland ---
bind = $mainMod, ESCAPE, exec, hyprlock
bind = $mainMod, L, exit
