general {
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 2
    blur_size = 2
    brightness = 0.9
}

auth {
    pam {
        enabled = true
    }

    fingerprint {
        enabled = true
        ready_message = Scan fingerprint to unlock
        present_message = Scanning...
        retry_delay = 250
    }
}

input-field {
    monitor =
    size = 280, 50
    position = 0, -80
    dots_center = true
    fade_on_empty = false
    outer_color = rgb(189, 147, 249)
    inner_color = rgb(68, 71, 90)
    font_color = rgb(248 248, 242)
    check_color = rgb (80, 250, 123)
    outline_thickness = 3
    rounding = 10
    fail_color = rgb(255, 85, 85)
    placeholder_text = 
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M:%S"
    color = rgb(248, 248, 242)
    font_size = 64
    font_family = JetBrainsMono Nerd Font
    position = 0, 120
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%Y.%m.%d"
    color = rgb(189, 147, 249)
    font_size = 16
    font_family = JetBrainsMono Nerd Font
    position = 0, 65
    halign = center
    valign = center
}
