preload = /home/robin/.dotfiles/.config/hypr/wallpapers/purple_black_hole.png
splash = false

wallpaper {
    monitor =
    path = /home/robin/.dotfiles/.config/hypr/wallpapers/purple_black_hole.png
}
